server:
  port: ${PORT:8000}

spring:
  application:
    name: VIRTUAL_YOUR_ASSET

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      data-source-properties:
        sslmode: require

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: flyway

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: viraasst@gmail.com
    password: rzrg qodc gfmd xspk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%.-12X{traceId},%.-8X{spanId}] %logger{36} : %msg%n"
  level:
    org:
      hibernate:
        SQL: off

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

crypto:
  secret-key: 1234567890123456