spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.application.name=Virtual Your Asset

# Config DB
spring.datasource.url=jdbc:postgresql://localhost:5432/vyra
spring.datasource.username=postgres
spring.datasource.password=qwerty
server.port=8000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#swagger
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs