server:
  port: 8000

spring:
  application:
    name: virtual-your-asset

  datasource:
    url: jdbc:postgresql://localhost:5432/vyra
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: viraasst@gmail.com
    password: rzrg qodc gfmd xspk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: off