#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: vyra-app
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: vyra-app
#  template:
#    metadata:
#      labels:
#        app: vyra-app
#    spec:
#      containers:
#        - name: vyra-container
#          image: azharhaikal/virtual-your-asset:latest
#          ports:
#              - containerPort: 8000
#          env:
#            - name: DB_URL
#              value: jdbc:postgresql://postgres-db:5432/vyra
#            - name: DB_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: vyra-db-secret
#                  key: username
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: vyra-db-secret
#                  key: password
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vyra-service
#spec:
#  type: LoadBalancer # Ini yang memberikan IP Publik agar bisa diakses Mobile
#  ports:
#    - port: 80
#      targetPort: 8000
#  selector:
#    app: vyra-app